### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by mistr140** [renzuzu/renzu_hud#10]
If I drive up to max and then sharply shift to the stage of neutral and still hold W the car brakes but then it goes on and behaves like a vending machine.

https://youtu.be/-FRYSkc5J28

**Comment by renzuzu** [comment]
what vending machine means?

i see in the video you downshift from 5th gear to 1st gear. it will normally act like that. in real life you gearbox might explode.
if you looking for 5th gear to neutral is not possible yet.

as i made this for up down up down (sequential)

**Comment by mistr140** [comment]
the point is that it can be changed from manual to automatic

**Comment by mistr140** [comment]
Suggestion: if a player steps down so hard to destroy the gearbox and would have to be replaced by a mechanic

**Comment by renzuzu** [comment]
closing for now, all vehicle unique feature in HUD will be transfer out to renzu_customs
inlcluding the manual tranny, so when its transfered i will do the destroy thing..
