### ISSUE TITLE
bodystatus, carcontrol vehiclestatus not working ?

### ISSUE THREAD

**Issue by fiesi** [renzuzu/renzu_hud#110]
Hello,,,

i am use the latest qbcore und i testet your Hud.
Its very very nice but i have Problems with bodystatus, carcontrol, carlock  and vehiclestatus.

This is not working?
I see no Error or so in the Console (Client/Server)

The den dependencys are installed...

**Comment by renzuzu** [comment]
i removed that features in the latest version..
if you want carcontrol use renzu_controller.
vehicle status, renzu_tuners :D

bodystatus which is i havent create a standalone resource yet..

sadly base on the years i manage the HUD. having that all feature is not performant to server and to client at all.
now is only client base. and HUD only for status and carhud
