### ISSUE TITLE
dragui

### ISSUE THREAD

**Issue by majidmazaheri** [renzuzu/renzu_hud#15]
some of my players when getting in a car as a driver the dragui activates and they can't drive the car then when they press ESC the dragui disappears but the vehicle engine won't turn on, whats the problem?

**Comment by renzuzu** [comment]
turn off the push to start function in config.

**Comment by renzuzu** [comment]
and also do update ,sounds like your behind in many updates

**Comment by majidmazaheri** [comment]
Thanks for the quick response, I will try this thanks again
