### ISSUE TITLE
Cloting bug

### ISSUE THREAD

**Issue by mistr140** [renzuzu/renzu_hud#16]
https://youtu.be/sYfIjDzSmk4

**Comment by majidmazaheri** [comment]
I have this problem too

**Comment by renzuzu** [comment]
i need proper repro using the latest version.
you probably have incorrect configuration?
the table is nil from your video error, which is the animation from clothing variants, (its from config)

mines work without problem
https://streamable.com/ucz64k (DEFAULT CONFIG)

**Comment by renzuzu** [comment]
re open when theres a repro
