### ISSUE TITLE
health and armor are not showing

### ISSUE THREAD

**Issue by MrForgetfulz** [renzuzu/renzu_hud#18]
Hello, do you know why is this buggy:
Health and armor are not showing when is it on type: "1"
![unknown](https://user-images.githubusercontent.com/91427649/134816452-461175b1-9856-4829-bf00-819768f7ab66.png)
It only works at type: "0"
![2](https://user-images.githubusercontent.com/91427649/134816524-f7937b86-bea4-4939-8cfe-77add0af309f.png)
Do you know how can i fix that to work properly

**Comment by renzuzu** [comment]
any repro? default config?

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_hud/commit/510b4a32446964e09322c095851496bbd7894732

Must be related to this updated

**Comment by MrForgetfulz** [comment]
It is on default config, sorry for not responding

**Comment by MrForgetfulz** [comment]
Can i somehow contact you to share you a screen to explain a problem cuz i think its really fuc*ed up for me :(..
