### ISSUE TITLE
Vehicle HUD & Keybinds

### ISSUE THREAD

**Issue by NotAimeri** [renzuzu/renzu_hud#19]
The Vehicle HUD works for some people in my server, but not others.  It will display for them after changing it in the F9 menu, but will not work.  When they drive, the speedometer does not update, etc.

Also, at the top of the keybinds config it says to edit it before running the script.  I unfortunately did not notice that before hand (my fault, I realize).  Is there a place to edit these keybinds after?  I cannot seem to find it.

**Comment by renzuzu** [comment]
Rename commands for keybinds too
It will work..

I need more info about speedometer.
Like f8 client so it would be helpful

**Comment by renzuzu** [comment]
Isue must be related to recent hud position
