### ISSUE TITLE
can't change keybind

### ISSUE THREAD

**Issue by refky21** [renzuzu/renzu_hud#2]
when i change some keybind, example show status, i want to change it to F9 it doesn't work, still keep using INSERT

**Comment by renzuzu** [comment]
This is why asked people to read config first and change the necessary things like keybinds

Once you start the script
The keybinds are saved to your local storage.
This is gta or fivem thing
I cant do anything on it.

To fixed this you need to clear cache or if there is some keybinds resets i am not sure.
