### ISSUE TITLE
QBCore framework

### ISSUE THREAD

**Issue by balcer64** [renzuzu/renzu_hud#20]
it does not work correctly with
the QBCore framework, switched to "oxmysql", "ghmattimysql" is no longer used, the speedometer also does not work (the picture is there, the speed is not displayed), the street display and some indicators do not work

**Comment by renzuzu** [comment]
oxmysql is supported now in latest branch.

try again and tell me other issue still persist and do put screenshots of F8 and repro to be helpful of fixing it

Thank you

**Comment by balcer64** [comment]
> В последней ветке теперь поддерживается oxmysql.
> 
> попробуйте еще раз и скажите мне, что другая проблема все еще сохраняется, и поместите скриншоты F8 и воспроизведения, чтобы помочь исправить это
> 
> Спасибо

this is fire) the speedometer and all indicators on the car are working (fuel consumption, seat belt, turn signals) You forgot to add and change line 13 of the configuration.MySQL in "oxmysql" in the instructions. The HUD of the player does not work, the icons do not respond to food and water intake, the health icon works, endurance did not understand, something is changing. There are no errors on the player's HUD, only writes something about the car:
[38;5;42m[      script:oxmysql] [ERROR] renzu_hud was unable to execute a query!
[38;5;42m[      script:oxmysql]         Table 'qbcore.owned_vehicles' doesn't exist
[38;5;42m[      script:oxmysql]         SELECT owner FROM owned_vehicles WHERE UPPER(plate)='5MV678QQ'
[38;5;218m[    script:renzu_hud] SCRIPT ERROR: @renzu_hud/server/server.lua:181: attempt to get length of a nil value (local 'owner')
[38;5;218m[    script:renzu_hud] > f (@oxmysql/oxmysql.js:1)
[38;5;218m[    script:renzu_hud] > <unknown> (@oxmysql/oxmysql.js:1)
[38;5;218m[    script:renzu_hud] > processTicksAndRejections (node:internal/process/task_queues:96)
[38;5;218m[    script:renzu_hud] > f (@oxmysql/oxmysql.js:1)
[38;5;218m[    script:renzu_hud] > <unknown> (@oxmysql/oxmysql.js:1)
[38;5;218m[    script:renzu_hud] > processTicksAndRejections (node:internal/process/task_queues:96)
![f8](https://user-images.githubusercontent.com/22128071/135721226-3a2e1285-d275-4740-a72e-0d08cd333462.jpg)
![hud](https://user-images.githubusercontent.com/22128071/135721227-08b47036-79fe-42a1-9d76-17f12ed8f8a9.jpg)

**Comment by renzuzu** [comment]
your using a qbcore config right?
did you setup this too.

the error you have in SQL is from vehicle tables.

```in conf folder check this```
main.lua
![image](https://user-images.githubusercontent.com/82306584/135722585-9da89603-c6d0-4a9a-8e9c-b9407976e855.png)
and set this to FALSE for now (lets make sure its working first) 
stratus.lua
![image](https://user-images.githubusercontent.com/82306584/135722608-8463bc8a-f41c-4566-b0a7-413e7a1ae96c.png)

**Comment by balcer64** [comment]
the HUD has earned, reacts to food intake, but there are still errors in the logs
![Screenshot_3](https://user-images.githubusercontent.com/22128071/135725486-fe9f167f-791f-4b5d-9d97-1581449f5398.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/22128071/135725488-7e8b9054-bc4d-40bf-87a7-56e4d1bf6581.jpg)
[fxserver.log](https://github.com/renzuzu/renzu_hud/files/7271846/fxserver.log)

**Comment by balcer64** [comment]
QBCore framework does not use STEAM, and added new functions, removed from files: "qbcore = nil" replaced with:"local QBCore = exports['qb-core']:GetCoreObject()
"-- Getters
-- Get your player first and then trigger a function on them
-- ex: local player = QBCore.Functions.GetPlayer(source)
-- ex: local example = player.Functions.functionname(parameter)

**Comment by renzuzu** [comment]
the error from logs is the owner column

you need to replace this

> `in conf folder check this`
> main.lua
> ![image](https://user-images.githubusercontent.com/82306584/135722585-9da89603-c6d0-4a9a-8e9c-b9407976e855.png)
> in qbcore its using `license` for owner and ` player_vehicles` instead of owned_vehicles

you can replace owner with license or citizenid

**Comment by xOGvKillax** [comment]
This HUD is really fire. I can't seem to get the rpm and speedometer and other gauges to work. I am on QBCORE framework. Everything else is working with it except the status bars for health, amor food, etc.
