### ISSUE TITLE
An error happen for the query

### ISSUE THREAD

**Issue by Kathou99** [renzuzu/renzu_hud#21]
When I rebbot the server I have this error 
does it's affect the hud?

[  script:mysql-async] [MySQL] [ERROR] [QLife_hud] An error happens for query "			CREATE TABLE IF NOT EXISTS `vehicle_status` (
[  script:mysql-async] 				`stats` LONGTEXT NULL DEFAULT '[]' COLLATE 'utf8mb4_general_ci',
[  script:mysql-async] 				`plate` VARCHAR(64) NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
[  script:mysql-async] 				`owner` VARCHAR(64) NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
[  script:mysql-async] 				PRIMARY KEY (`plate`) USING BTREE
[  script:mysql-async] 			)
[  script:mysql-async] 			COLLATE='utf8mb4_general_ci'
[  script:mysql-async] 			ENGINE=InnoDB
[  script:mysql-async] 			;
[  script:mysql-async] 			CREATE TABLE IF NOT EXISTS `body_status` (
[  script:mysql-async] 				`status` LONGTEXT NULL DEFAULT '[]' COLLATE 'utf8mb4_general_ci',
[  script:mysql-async] 				`identifier` VARCHAR(64) NULL DEFAULT '' COLLATE 'utf8mb4_general_ci',
[  script:mysql-async] 				PRIMARY KEY (`identifier`) USING BTREE
[  script:mysql-async] 			)
[  script:mysql-async] 			COLLATE='utf8mb4_general_ci'
[  script:mysql-async] 			ENGINE=InnoDB
[  script:mysql-async] 			;
[  script:mysql-async] 		 : []": ER_BLOB_CANT_HAVE_DEFAULT: BLOB 'stats' ne peut avoir de valeur par défaut
[    script:renzu_hud] -------------
[    script:renzu_hud] RENZU HUD STARTED!
[    script:renzu_hud] FRAMEWORK: ESX
[    script:renzu_hud PLAYER VEHICLES TABLE: owned_vehicles
[    script:renzu_hud] IDENTIFIER TO USE: license:
[    script:renzu_hud]

**Comment by renzuzu** [comment]
You can comment that part out from server.lua

Its the auto import
Does not need if you already have it
