### ISSUE TITLE
How to chaange hud possition

### ISSUE THREAD

**Issue by TheShadowPL** [renzuzu/renzu_hud#5]
I have trouble witch changing status hud disaplay when i'm changing in config and looks like that 
![image](https://user-images.githubusercontent.com/39172218/128850798-d6709008-fca7-44a0-b32b-ccc1057da085.png)
can you tell me where i can change please :)

**Comment by renzuzu** [comment]
You can adjust css
Or in function lua

Or you can wait for my update

**Comment by renzuzu** [comment]
HUD has now a settings 
/hud or F9
