### ISSUE TITLE
errors in sever console when nonowned vehicle

### ISSUE THREAD

**Issue by Velkostatkar** [renzuzu/renzu_hud#53]
Hello

now I catch this error message in console when player steal not owned car. 
The error propably have no any affect but just for info I post it here so you can maybe just clear it in future.

[ script:renzu_hud] plate is nil
[ script:renzu_hud] plate is nil
[ c-scripting-core] InvokeNative: execution failed: Tried to access invalid entity: 133178
[ script:renzu_garage] SCRIPT ERROR: Execution of native 00000000e8522d58 in script host failed: Tried to access invalid entity: 133178
[ script:renzu_garage] &gt; handler (@renzu_garage/server/server.lua:1291)
[ c-scripting-core] InvokeNative: execution failed: Tried to access invalid entity: 133178
[script:renzu_stancer] SCRIPT ERROR: Execution of native 00000000e8522d58 in script host failed: Tried to access invalid entity: 133178
[script:renzu_stancer] &gt; handler (@renzu_stancer/server.lua:124)
[ c-scripting-core] InvokeNative: execution failed: Tried to access invalid entity: 133178
[ script:renzu_nitro] SCRIPT ERROR: Execution of native 00000000e8522d58 in script host failed: Tried to access invalid entity: 133178
[ script:renzu_nitro] &gt; handler (@renzu_nitro/server.lua:209)
[ c-scripting-core] InvokeNative: execution failed: Tried to access invalid entity: 133178
[ script:renzu_engine] SCRIPT ERROR: Execution of native 00000000e8522d58 in script host failed: Tried to access invalid entity: 133178
[ script:renzu_engine] &gt; handler (@renzu_engine/server.lua:180)
[ c-scripting-core] InvokeNative: execution failed: Tried to access invalid entity: 133178
[ script:renzu_turbo] SCRIPT ERROR: Execution of native 00000000e8522d58 in script host failed: Tried to access invalid entity: 133178
[ script:renzu_turbo] &gt; handler (@renzu_turbo/server.lua:164)
[ script:renzu_hud] plate is nil
[ script:renzu_hud] plate is nil

**Comment by renzuzu** [comment]
Update the vehicle kita its already fix.

The entity invalid error is a server error
When accessing a deleted entity eg. Vehicle
