### ISSUE TITLE
License query

### ISSUE THREAD

**Issue by KingMascotte** [renzuzu/renzu_hud#6]
Hey there,

I came across this resource when researhing HUDs created as close as possible to standalone. I'm wondering what license this is released under so as to being able to use it as part of a custom framework I'm creating for FiveM - which of course, when it reaches a stable build suitable for release, being entirely open sourced.

Great work, I really admire the level of detail put into the HUD!

**Comment by renzuzu** [comment]
thank you for kind words.

yeah this actually under GPL License 3.0

Great to hear the about the custom framework.

is the framework is Open Source in public?

**Comment by KingMascotte** [comment]
Thanks for the clarification!

It's not public just yet until it's in a more stable working condition. I need to clean up and divide the code into modules for efficieny first. So hopefully in the next 3/4 weeks it'll be ready to release publicly as a WIP :)
